name: Test Manual Approval Action
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: roeezolantz/manual-approval-action@main
        with:
          files: 'CHANGELOG.md'
          emoji: '🚀'
          required: 'true'
          timeout: '300'
          poll-interval: '10'
